name: Build and Deploy Unity Web

on:
  push:
    branches:
      - staging
      - main

jobs:

  # ---------- BUILD JOB ----------
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build WebGL on my Mac
        run: >
          "/Applications/Unity/Hub/Editor/2022.3.62f3/Unity.app/Contents/MacOS/Unity" 
          -batchmode -quit -projectPath . 
          -executeMethod UnityEditor.BuildPipeline.BuildPlayer 
          -buildTarget WebGL 
          -logFile buildlog.txt 
          -customBuildTarget WebGL 
          -customBuildName WebGL 
          -customBuildPath build/WebGL

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL/


  # ---------- STAGING DEPLOY ----------
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: WebGL-Build
          path: webgl

      - name: Configure AWS Credentials (STAGING)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-east-1

      - name: Sync build to STAGING bucket
        run: |
          cd webgl
          echo "Uploading WebGL build to staging.haldom.net ..."
          aws s3 sync . s3://staging.haldom.net/ --delete --acl public-read

      - name: Invalidate STAGING CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id d2qchnc5zprwef \
            --paths "/*"


  # ---------- PRODUCTION DEPLOY ----------
  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: WebGL-Build
          path: webgl

      - name: Configure AWS Credentials (PRODUCTION)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync build to PRODUCTION bucket
        run: |
          cd webgl
          echo "Uploading WebGL build to haldom.net ..."
          aws s3 sync . s3://haldom.net/ --delete --acl public-read

      - name: Invalidate PRODUCTION CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E25J6ZW46HS9ZK \
            --paths "/*"
